APP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url,include
from APP import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^home/',include(('home.urls','home'),namespace='home')),

    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView

app_name = 'accounts'

urlpatterns= [

    url( r'^login/$', LoginView.as_view(template_name="accounts/login.html"), name="login"),
    url( r'^logout/$', LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    url(r'^register/$',views.register, name='register'),
    url(r'^profile/(?P<pk>\d+)/$',views.view_profile , name='view_profile_with_pk'),
    url(r'^profile/$',views.view_profile , name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    url(r'^change-password/$',views.change_password,name='change_password'),
    url(r'^reset-password/$',PasswordResetView.as_view( template_name='accounts/reset_password.html',
        email_template_name='accounts/reset_password_email.html', success_url=reverse_lazy('accounts:password_reset_done')
    ),name="reset_password"),
    url(r'^reset-password/done/$',PasswordResetDoneView.as_view(template_name="accounts/reset_password_done.html"),name="password_reset_done"),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',PasswordResetConfirmView.as_view(template_name="accounts/reset_password_confirm.html",success_url=reverse_lazy('accounts:password_reset_complete')), name="password_reset_confirm"),
    url(r'^reset-password/complete/$',PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"),name="password_reset_complete"),

    ]

home/urls.py
from django.conf.urls import url
from django.urls import path
from home.views import HomeView,PostDetailView,PostCreateView, PostUpdateView , PostDeleteView ,friends_list

from . import views

urlpatterns= [
    url(r'^$',HomeView.as_view() , name='home'),
    url(r'^friends/$', friends_list.as_view()),
    path('post/<int:pk>/', PostDetailView.as_view() ,name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view() ,name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view() ,name='post-delete'),
    path('post/new/', PostCreateView.as_view() ,name='post-create'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friend,name='change_friend'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    created= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('home:post-detail', kwargs={'pk': self.pk})


class Friend(models.Model):
    users= models.ManyToManyField(User)
    current_user= models.ForeignKey(User, related_name='owner',null=True,on_delete='CASCADE')

    @classmethod
    def make_friend(cls, current_user , new_friend):
        friend, created= cls.objects.get_or_create(
        current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user , new_friend):
        friend, created= cls.objects.get_or_create(
        current_user=current_user
        )
        friend.users.remove(current_user,new_friend)

home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post= forms.CharField(widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'placeholder':'Write a post....'
        }
    ))

    class Meta:
        model = Post
        fields = ('post',)

home/views.py
from django.views.generic import TemplateView, DetailView, CreateView, UpdateView,DeleteView
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin , UserPassesTestMixin
from home.forms import HomeForm
from home.models import Post,Friend

class HomeView(TemplateView):
    template_name= 'home/home.html'

    def get(self,request):
        form = HomeForm()
        posts= Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        try:
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()
        except Friend.DoesNotExist:
            friends=None
            pass
        ##friends = Friend.objects.get(current_user=request.user)


        args={'form':form,'posts': posts,'users': users, 'friends':friends}
        return render(request,self.template_name, args)

    def post(self,request):
        form= HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text= form.cleaned_data['post']
            form=HomeForm()
            return redirect('home:home')

        args= {'form':form , 'text':text}
        return render(request,self.template_name,args)

def change_friend(request,operation,pk):
    friend=User.objects.get(pk=pk)
    if operation =='add':
        Friend.make_friend(request.user,friend)
    elif operation =='remove':
        Friend.lose_friend(request.user,friend)
    return redirect('home:home')



class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['post']

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['post']

    def form_valid(self,form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post=self.get_object()
        if self.request.user==post.user:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url='/home/'
    def test_func(self):
        post=self.get_object()
        if self.request.user==post.user:
            return True
        return False

class friends_list(TemplateView):
    template_name= 'home/friends.html'

    def get(self,request):
        users = User.objects.exclude(id=request.user.id)
        try:
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()
        except Friend.DoesNotExist:
            friends=None
            pass
        args={'users': users, 'friends':friends}
        return render(request,self.template_name, args)

home/templates/home/friends.html
{% extends 'base.html' %}
{% block body %}
<div class="col-md-4">
  <h2 style="color:Black;">Other People</h2>
  {% for user in users %}
    {% if user not in friends %}
      <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
        <h3 style="color:Black;">{{ user.username }}</h3>
      </a>
      {% endif %}
      {% if not user in friends %}
      <a href="{% url 'home:change_friend' operation='add' pk=user.pk %}">
        <button type="button" class="btn btn-success" ">Add Friend</button>
      </a>
      {% endif %}
  {% endfor %}
  <br>
  <br>
  <h2 style="color:Black;">Friends</h2>
  {% for friend in friends %}
      <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
        <h3 style="color:Black;">{{ friend.username }}</h3>
      </a>
      <a href="{% url 'home:change_friend' operation='remove' pk=friend.pk %}">
        <button type="button" class="btn btn-danger" ">Remove Friend</button>
      </a>

  {% endfor %}
</div>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    <div class="col-md-8">
      <h1>Home</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.post }}
        <br>
        <button type="submit">Submit</button>
      </form>
      <!-- <h2>{{ text }}</h2> -->
      {% for post in posts %}
          <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.user.userprofile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'accounts:view_profile_with_pk' pk=post.user.id %}">{{ post.user.get_full_name }}</a>

              <small class="text-muted">{{ post.created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'home:post-detail' post.id %}">{{ post.post }}</a></h2>
            <!-- <p class="article-content">{{ post.post }}</p> -->
          </div>
        </article>
      {% endfor %}
    </div>

</div>
{% endblock %}

home/templates/home/post_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <form  method="post">
    {% csrf_token %}
    <h2>Are you Sure, you want to delete: "{{object.post}}"</h2>
      <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
      <a class="btn btn-outline-secondary" href="{% url 'home:post-detail' object.id %}">Cancel</a>

  </form>
</div>
{% endblock %}

home/templates/home/post_detail.html
{% extends 'base.html' %}

{% block body %}
          <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ object.user.userprofile.image.url }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="#">{{ object.user.get_full_name }}</a>
                <small class="text-muted">{{ object.created|date:"F d, Y" }}</small>
                {% if object.user == user %}
                <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'home:post-update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'home:post-delete' object.id %}">Delete</a>
              </div>
                {% endif %}
              </div>
             <h2 class="article-title">{{ object.post }}</h2>
              <!-- <p class="article-content">{{ object.post }}</p> -->
            </div>
        </article>

{% endblock %}

home/templates/home/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
  <form  method="post">
    {% csrf_token %}
    {{form|crispy }}
      <button type="submit">Post</button>
  </form>
</div>
{% endblock %}