APP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url,include
from APP import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^$',views.login_redirect, name='login_redirect'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^home/',include(('home.urls','home'),namespace='home')),

    path('admin/', admin.site.urls),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView

app_name = 'accounts'

urlpatterns= [

    url( r'^login/$', LoginView.as_view(template_name="accounts/login.html"), name="login"),
    url( r'^logout/$', LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    url(r'^register/$',views.register, name='register'),
    url(r'^profile/(?P<pk>\d+)/$',views.view_profile , name='view_profile_with_pk'),
    url(r'^profile/$',views.view_profile , name='view_profile'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    url(r'^change-password/$',views.change_password,name='change_password'),
    url(r'^reset-password/$',PasswordResetView.as_view( template_name='accounts/reset_password.html',
        email_template_name='accounts/reset_password_email.html', success_url=reverse_lazy('accounts:password_reset_done')
    ),name="reset_password"),
    url(r'^reset-password/done/$',PasswordResetDoneView.as_view(template_name="accounts/reset_password_done.html"),name="password_reset_done"),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',PasswordResetConfirmView.as_view(template_name="accounts/reset_password_confirm.html",success_url=reverse_lazy('accounts:password_reset_complete')), name="password_reset_confirm"),
    url(r'^reset-password/complete/$',PasswordResetCompleteView.as_view(template_name="accounts/reset_password_complete.html"),name="password_reset_complete"),

    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='kanpur')

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city= models.CharField(max_length=100,default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(default='default.jpg', upload_to='profile_image',blank=True)


    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile=UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model =User
        fields = (
        'username',
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2'
        )
    def save(self,commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name= self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
        'email',
        'first_name',
        'last_name',
        'password',
        )

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model= UserProfile
        fields = ['image']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from accounts.forms import RegistrationForm,EditProfileForm,ProfileUpdateForm
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login')
    else:
        form=RegistrationForm()
    args = {'form':form}
    return render(request,'accounts/reg_form.html', args)

@login_required
def view_profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user= request.user
    args = {'user':user}
    return render(request,'accounts/profile.html',args)


@login_required
def edit_profile(request):
    if request.method=='POST':
        p_form= ProfileUpdateForm(request.POST , request.FILES , instance=request.user.userprofile)
        form =EditProfileForm(request.POST,instance=request.user)
        if form.is_valid() and p_form.is_valid():
            form.save()
            p_form.save()
            return redirect('/accounts/profile')
    else:
        p_form= ProfileUpdateForm(instance=request.user.userprofile)
        form=EditProfileForm(instance=request.user)
    args ={'form':form, 'p_form':p_form}
    return render(request,'accounts/edit_profile.html',args)

@login_required
def change_password(request):
    if request.method=='POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/accounts/profile')
        else:
            return redirect('/accounts/change_password')
    else:
        form=PasswordChangeForm(user=request.user)
    args ={'form':form}
    return render(request,'accounts/change_password.html',args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

    {%block head %}
    <title>Profile</title>
    {%endblock %}

    {% block body %}
    <div class="container">
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Submit</button>
        </form>
        <br>
      </div>

    {% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

    {%block head %}
    <title>Profile</title>
    {%endblock %}

    {% block body %}
  
      <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{ user.userprofile.image.url }}">
          <div class="media-body">
            <h2 class="account-heading">{{ user.first_name}}</h2>
            <p class="text-secondary">{{user.email}}</p>
          </div>
        </div>
        <form  method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form|crispy }}
          {{ p_form|crispy }}

            <button type="submit">Update</button>
        </form>
  </div>

    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
<h1>Welcome</h1>
<p>
  you can login in here.
</p>
<h2>Login</h2>

<form method="post">
  {% csrf_token %}
  {{form|crispy}}
  <button type="submit">Login</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Logged out</h1>
<p>
  You have to logged out.
</p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

    {%block head %}
    <title>Profile</title>
    {%endblock %}

    {% block body %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.userprofile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user }}</h2>
          <p class="text-secondary">FirstName : {{user.first_name}}</p>
          <p class="text-secondary">LastName :{{user.last_name}}</p>
          <p class="text-secondary">Email :{{user.email}}</p>
          <p class="text-secondary">City : {{user.userprofile.city}}</p>
        </div>
      </div>
  <!-- FORM HERE -->
</div>
  

    {% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
  <h1>Register</h1>
  <form  method="post">
    {% csrf_token %}
    {{form|crispy }}
      <button type="submit">Sign Up</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Reset Password</h1>
<p>
  Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
</p>
<h2>Login</h2>

<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Reset password</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Password reset Complete</h1>
  <p>
  </p>
    <a href="/accounts">login</a>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Enter New Password</h1>
<p>
</p>

<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Reset password</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}
{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}